library(aspe) #renv::install("PascalIrz/aspe")
library(car)
library(cluster)
library(data.table)
library(dendextend)
library(factoextra)
library(equatiomatic) #renv::install("datalorax/equatiomatic")
#library(gplots)
library(ggcorrplot)
library(ggplot2)
library(ggspatial)
library(ggtext)
library(lindia)
library(MASS)
library(Metrics)
library(patchwork)
library(qs)
library(quantreg)
library(raster)
library(readxl)
library(rgdal)
library(rprojroot)
library(sf)
library(spatialreg)
library(spdep)
library(stringr)
library(targets)
library(terra)
library(tidyterra)

#Possible packages for visuals:
#https://mjskay.github.io/ggdist/
#